# SPDX-FileCopyrightText: 2022 Johannes Loher
#
# SPDX-License-Identifier: MIT

name: Release

on:
  release:
    types: [published]

env:
  package_type: module

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create zip file
        working-directory: .
        run: zip -r ./${{ env.package_type }}.zip .

      - name: Create release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './${{ env.package_type }}.json, ./${{ env.package_type }}.zip'
          body: ${{ github.event.release.body }}